theme: minima
title: Garrett Ordner
author: Garrett Ordner
description: > # this means to ignore newlines until "baseurl:"
  Garrett Ordner's personal website. Currently under construction.

# social links
github_username:  garrett-ordner # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
